Repository ManageIQ/manageiq-providers-awx, pull requests merged in 2024-02, with the labels that each got.

#23 Drop require_nested
  app/models/manageiq/providers/awx/automation_manager.rb
  app/models/manageiq/providers/awx/automation_manager/event_catcher.rb
  app/models/manageiq/providers/awx/automation_manager/job.rb
  app/models/manageiq/providers/awx/automation_manager/refresh_worker.rb
  app/models/manageiq/providers/awx/automation_manager/workflow_job.rb
  app/models/manageiq/providers/awx/inventory.rb
  app/models/manageiq/providers/awx/inventory/collector.rb
  app/models/manageiq/providers/awx/inventory/parser.rb
  app/models/manageiq/providers/awx/inventory/persister.rb
Labels: rails7, technical debt

#24 Add supports :update/:delete to AWX Credential
  app/models/manageiq/providers/awx/automation_manager/credential.rb
Labels: refactoring

#25 Test with ruby 3.1 and 3.0
  .github/workflows/ci.yaml
Labels: test

#26 [RADJABOV] Test radjabov with ruby 3.1
  .github/workflows/ci.yaml
Labels: test, ruby3.1
